title: Marcelo Y. B. Hossomi
url: 'https://hossomi.github.io'

collections_dir: content
collections:
  pt:
    output: true
    permalink: /:collection/:slug
  en:
    output: true
    permalink: /:collection/:slug

defaults:
  language: pt